### ISSUE TITLE
MAPA MENTAL BETSABE ARICEL CASTRO RODRIGUEZ 1BS

### ISSUE THREAD

**Issue by ARICELCASTRO1999** [SistemasTecTlaxiaco/actividad-1-mapa-mental-ARICELCASTRO1999#1]
[MAPA MENTAL INVESTIGACION DOCUMENTAL BETSABE ARICEL CASTRO RODRIGUEZ 1BS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-ARICELCASTRO1999/files/9466298/MAPA.MENTAL.INVESTIGACION.DOCUMENTAL.BETSABE.ARICEL.CASTRO.RODRIGUEZ.1BS.pdf)

**Comment by 11042002** [comment]
Tu calificación es de: 17.6

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
